### ISSUE TITLE
NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres

### ISSUE THREAD

**Issue by krrishdholakia** [supabase/vecs#25]
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    vx = vecs.create_client(DB_CONNECTION)
  File "/home/runner/StarryKindSphere/venv/lib/python3.10/site-packages/vecs/__init__.py", line 14, in create_client
    return Client(connection_string)
  File "/home/runner/StarryKindSphere/venv/lib/python3.10/site-packages/vecs/client.py", line 16, in __init__
    self.engine = create_engine(connection_string)
  File "<string>", line 2, in create_engine
  File "/home/runner/StarryKindSphere/venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/home/runner/StarryKindSphere/venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 552, in create_engine
    entrypoint = u._get_entrypoint()
  File "/home/runner/StarryKindSphere/venv/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 754, in _get_entrypoint
    cls = registry.load(name)
  File "/home/runner/StarryKindSphere/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 368, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres


**Comment by krrishdholakia** [comment]
Tried running this in Replit and Google Colab, saw the same error in both places.

**Comment by krrishdholakia** [comment]
fixed by changes `postgres` to `postgresql`
